# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "connect_to_telebit": "00_core.ipynb",
         "connect_to_localtunel": "00_core.ipynb",
         "connect_to_ngrok": "00_core.ipynb",
         "execute_cmd": "00_core.ipynb",
         "mount_drive": "00_core.ipynb",
         "setup_vscode": "00_core.ipynb",
         "setup_julia": "00_core.ipynb",
         "install_jupyter_extension": "00_core.ipynb",
         "RemoteExecutor": "00_core.ipynb",
         "EXTENSIONS": "00_core.ipynb",
         "RemoteCode": "00_core.ipynb",
         "NOTEBOOK_EXTENSIONS": "00_core.ipynb",
         "SERVER_EXTENSIONS": "00_core.ipynb",
         "LAB_EXTENSIONS": "00_core.ipynb",
         "RemoteJupyter": "00_core.ipynb",
         "RemotePluto": "00_core.ipynb",
         "start_code": "01_cli.ipynb",
         "start_jupyter": "01_cli.ipynb",
         "start_pluto": "01_cli.ipynb",
         "get_icon_path": "02_proxyservers.ipynb",
         "switch_path": "02_proxyservers.ipynb",
         "fix_cmd": "02_proxyservers.ipynb",
         "plutoserver": "02_proxyservers.ipynb",
         "codeserver": "02_proxyservers.ipynb",
         "docserver": "02_proxyservers.ipynb",
         "bookserver": "02_proxyservers.ipynb",
         "setup_gh": "04_colab.ipynb",
         "RemoteProject": "04_colab.ipynb"}

modules = ["core.py",
           "cli.py",
           "proxyservers.py",
           "colab.py"]

doc_url = "https://remoteconnect.netlify.app/"

git_url = "https://github.com/rahuketu86/RemoteConnect/tree/master/"

def custom_doc_links(name): return None
