# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "start_code": "01_cli.ipynb"}

modules = ["core.py",
           "cli.py"]

doc_url = "https://remoteconnect.netlify.app"

git_url = "https://github.com/rahuketu86/RemoteConnect/tree/master/"

def custom_doc_links(name): return None
