# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_proxyservers.ipynb (unless otherwise specified).

__all__ = ['plutoserver', 'codeserver']

# Cell
from .core import setup_vscode

# Cell
def plutoserver():
    return {
        "command": ["julia", "--optimize=0", "-e", "import Pluto; Pluto.run(host=\"0.0.0.0\", port={port}, launch_browser=false, require_secret_for_open_links=false, require_secret_for_access=false)"],
        "timeout": 60,
        "launcher_entry": {
            "title": "Pluto.jl",
    },
  }

# Cell
def codeserver():
    """
    Export codeserver as jupyter server proxy
    """
    return {
        "command": ["code-server", "--port", "{port}", "--auth","none", "--disable-telemetry"],
        "timeout":60,
#         'absolute_url': True,
        "launcher_entry": {
            "title": "codeserver",
#             'icon_path': get_icon_path("vscode.svg")
    },
  }